var m = [{
        id: "Pacific/Niue",
        offset: -660
    }, {
        id: "Pacific/Midway",
        offset: -660
    }, {
        id: "Pacific/Pago_Pago",
        offset: -660
    }, {
        id: "Pacific/Rarotonga",
        offset: -600
    }, {
        id: "America/Adak",
        offset: -600
    }, {
        id: "Pacific/Honolulu",
        offset: -600
    }, {
        id: "Pacific/Tahiti",
        offset: -600
    }, {
        id: "Pacific/Marquesas",
        offset: -570
    }, {
        id: "America/Anchorage",
        offset: -540
    }, {
        id: "Pacific/Gambier",
        offset: -540
    }, {
        id: "America/Los_Angeles",
        offset: -480
    }, {
        id: "America/Tijuana",
        offset: -480
    }, {
        id: "America/Vancouver",
        offset: -480
    }, {
        id: "Pacific/Pitcairn",
        offset: -480
    }, {
        id: "America/Hermosillo",
        offset: -420
    }, {
        id: "America/Edmonton",
        offset: -420
    }, {
        id: "America/Ojinaga",
        offset: -420
    }, {
        id: "America/Denver",
        offset: -420
    }, {
        id: "America/Phoenix",
        offset: -420
    }, {
        id: "America/Whitehorse",
        offset: -420
    }, {
        id: "America/Belize",
        offset: -360
    }, {
        id: "America/Chicago",
        offset: -360
    }, {
        id: "America/Guatemala",
        offset: -360
    }, {
        id: "America/Managua",
        offset: -360
    }, {
        id: "America/Mexico_City",
        offset: -360
    }, {
        id: "America/Costa_Rica",
        offset: -360
    }, {
        id: "America/El_Salvador",
        offset: -360
    }, {
        id: "America/Regina",
        offset: -360
    }, {
        id: "America/Tegucigalpa",
        offset: -360
    }, {
        id: "America/Winnipeg",
        offset: -360
    }, {
        id: "Pacific/Easter",
        offset: -360
    }, {
        id: "Pacific/Galapagos",
        offset: -360
    }, {
        id: "America/Rio_Branco",
        offset: -300
    }, {
        id: "America/Bogota",
        offset: -300
    }, {
        id: "America/Havana",
        offset: -300
    }, {
        id: "America/Atikokan",
        offset: -300
    }, {
        id: "America/Cancun",
        offset: -300
    }, {
        id: "America/Grand_Turk",
        offset: -300
    }, {
        id: "America/Cayman",
        offset: -300
    }, {
        id: "America/Jamaica",
        offset: -300
    }, {
        id: "America/Nassau",
        offset: -300
    }, {
        id: "America/New_York",
        offset: -300
    }, {
        id: "America/Panama",
        offset: -300
    }, {
        id: "America/Port-au-Prince",
        offset: -300
    }, {
        id: "America/Toronto",
        offset: -300
    }, {
        id: "America/Guayaquil",
        offset: -300
    }, {
        id: "America/Lima",
        offset: -300
    }, {
        id: "America/Manaus",
        offset: -240
    }, {
        id: "America/St_Kitts",
        offset: -240
    }, {
        id: "America/Blanc-Sablon",
        offset: -240
    }, {
        id: "America/Montserrat",
        offset: -240
    }, {
        id: "America/Barbados",
        offset: -240
    }, {
        id: "America/St_Lucia",
        offset: -240
    }, {
        id: "America/Port_of_Spain",
        offset: -240
    }, {
        id: "America/Martinique",
        offset: -240
    }, {
        id: "America/St_Barthelemy",
        offset: -240
    }, {
        id: "America/Halifax",
        offset: -240
    }, {
        id: "Atlantic/Bermuda",
        offset: -240
    }, {
        id: "America/St_Vincent",
        offset: -240
    }, {
        id: "America/Kralendijk",
        offset: -240
    }, {
        id: "America/Guadeloupe",
        offset: -240
    }, {
        id: "America/Marigot",
        offset: -240
    }, {
        id: "America/Aruba",
        offset: -240
    }, {
        id: "America/Lower_Princes",
        offset: -240
    }, {
        id: "America/Tortola",
        offset: -240
    }, {
        id: "America/Dominica",
        offset: -240
    }, {
        id: "America/St_Thomas",
        offset: -240
    }, {
        id: "America/Grenada",
        offset: -240
    }, {
        id: "America/Antigua",
        offset: -240
    }, {
        id: "America/Puerto_Rico",
        offset: -240
    }, {
        id: "America/Santo_Domingo",
        offset: -240
    }, {
        id: "America/Anguilla",
        offset: -240
    }, {
        id: "America/Thule",
        offset: -240
    }, {
        id: "America/Curacao",
        offset: -240
    }, {
        id: "America/La_Paz",
        offset: -240
    }, {
        id: "America/Santiago",
        offset: -240
    }, {
        id: "America/Guyana",
        offset: -240
    }, {
        id: "America/Asuncion",
        offset: -240
    }, {
        id: "America/Caracas",
        offset: -240
    }, {
        id: "America/St_Johns",
        offset: -210
    }, {
        id: "America/Argentina/Buenos_Aires",
        offset: -180
    }, {
        id: "America/Sao_Paulo",
        offset: -180
    }, {
        id: "Antarctica/Palmer",
        offset: -180
    }, {
        id: "America/Punta_Arenas",
        offset: -180
    }, {
        id: "Atlantic/Stanley",
        offset: -180
    }, {
        id: "America/Cayenne",
        offset: -180
    }, {
        id: "America/Miquelon",
        offset: -180
    }, {
        id: "America/Paramaribo",
        offset: -180
    }, {
        id: "America/Montevideo",
        offset: -180
    }, {
        id: "America/Nuuk",
        offset: -180
    }, {
        id: "America/Noronha",
        offset: -120
    }, {
        id: "Atlantic/South_Georgia",
        offset: -120
    }, {
        id: "Atlantic/Azores",
        offset: -60
    }, {
        id: "Atlantic/Cape_Verde",
        offset: -60
    }, {
        id: "America/Scoresbysund",
        offset: -60
    }, {
        id: "Africa/Abidjan",
        offset: 0
    }, {
        id: "Africa/Accra",
        offset: 0
    }, {
        id: "Africa/Bamako",
        offset: 0
    }, {
        id: "Africa/Bissau",
        offset: 0
    }, {
        id: "Africa/Conakry",
        offset: 0
    }, {
        id: "Africa/Dakar",
        offset: 0
    }, {
        id: "America/Danmarkshavn",
        offset: 0
    }, {
        id: "Europe/Isle_of_Man",
        offset: 0
    }, {
        id: "Europe/Dublin",
        offset: 0
    }, {
        id: "Africa/Freetown",
        offset: 0
    }, {
        id: "Atlantic/St_Helena",
        offset: 0
    }, {
        id: "Africa/Lome",
        offset: 0
    }, {
        id: "Europe/London",
        offset: 0
    }, {
        id: "Africa/Monrovia",
        offset: 0
    }, {
        id: "Africa/Nouakchott",
        offset: 0
    }, {
        id: "Africa/Ouagadougou",
        offset: 0
    }, {
        id: "Atlantic/Reykjavik",
        offset: 0
    }, {
        id: "Europe/Jersey",
        offset: 0
    }, {
        id: "Europe/Guernsey",
        offset: 0
    }, {
        id: "Africa/Banjul",
        offset: 0
    }, {
        id: "Africa/Sao_Tome",
        offset: 0
    }, {
        id: "Antarctica/Troll",
        offset: 0
    }, {
        id: "Africa/Casablanca",
        offset: 0
    }, {
        id: "Africa/El_Aaiun",
        offset: 0
    }, {
        id: "Atlantic/Canary",
        offset: 0
    }, {
        id: "Europe/Lisbon",
        offset: 0
    }, {
        id: "Atlantic/Faroe",
        offset: 0
    }, {
        id: "Africa/Windhoek",
        offset: 60
    }, {
        id: "Africa/Algiers",
        offset: 60
    }, {
        id: "Europe/Amsterdam",
        offset: 60
    }, {
        id: "Europe/Andorra",
        offset: 60
    }, {
        id: "Europe/Belgrade",
        offset: 60
    }, {
        id: "Europe/Berlin",
        offset: 60
    }, {
        id: "Europe/Malta",
        offset: 60
    }, {
        id: "Europe/Bratislava",
        offset: 60
    }, {
        id: "Europe/Brussels",
        offset: 60
    }, {
        id: "Europe/Budapest",
        offset: 60
    }, {
        id: "Europe/Copenhagen",
        offset: 60
    }, {
        id: "Europe/Gibraltar",
        offset: 60
    }, {
        id: "Europe/Ljubljana",
        offset: 60
    }, {
        id: "Arctic/Longyearbyen",
        offset: 60
    }, {
        id: "Europe/Luxembourg",
        offset: 60
    }, {
        id: "Europe/Madrid",
        offset: 60
    }, {
        id: "Europe/Monaco",
        offset: 60
    }, {
        id: "Europe/Oslo",
        offset: 60
    }, {
        id: "Europe/Paris",
        offset: 60
    }, {
        id: "Europe/Podgorica",
        offset: 60
    }, {
        id: "Europe/Prague",
        offset: 60
    }, {
        id: "Europe/Rome",
        offset: 60
    }, {
        id: "Europe/San_Marino",
        offset: 60
    }, {
        id: "Europe/Sarajevo",
        offset: 60
    }, {
        id: "Europe/Skopje",
        offset: 60
    }, {
        id: "Europe/Stockholm",
        offset: 60
    }, {
        id: "Europe/Tirane",
        offset: 60
    }, {
        id: "Africa/Tunis",
        offset: 60
    }, {
        id: "Europe/Vaduz",
        offset: 60
    }, {
        id: "Europe/Vatican",
        offset: 60
    }, {
        id: "Europe/Vienna",
        offset: 60
    }, {
        id: "Europe/Warsaw",
        offset: 60
    }, {
        id: "Europe/Zagreb",
        offset: 60
    }, {
        id: "Europe/Zurich",
        offset: 60
    }, {
        id: "Africa/Bangui",
        offset: 60
    }, {
        id: "Africa/Malabo",
        offset: 60
    }, {
        id: "Africa/Brazzaville",
        offset: 60
    }, {
        id: "Africa/Porto-Novo",
        offset: 60
    }, {
        id: "Africa/Douala",
        offset: 60
    }, {
        id: "Africa/Kinshasa",
        offset: 60
    }, {
        id: "Africa/Lagos",
        offset: 60
    }, {
        id: "Africa/Libreville",
        offset: 60
    }, {
        id: "Africa/Luanda",
        offset: 60
    }, {
        id: "Africa/Ndjamena",
        offset: 60
    }, {
        id: "Africa/Niamey",
        offset: 60
    }, {
        id: "Africa/Bujumbura",
        offset: 120
    }, {
        id: "Africa/Gaborone",
        offset: 120
    }, {
        id: "Africa/Harare",
        offset: 120
    }, {
        id: "Africa/Juba",
        offset: 120
    }, {
        id: "Africa/Khartoum",
        offset: 120
    }, {
        id: "Africa/Kigali",
        offset: 120
    }, {
        id: "Africa/Blantyre",
        offset: 120
    }, {
        id: "Africa/Lubumbashi",
        offset: 120
    }, {
        id: "Africa/Lusaka",
        offset: 120
    }, {
        id: "Africa/Maputo",
        offset: 120
    }, {
        id: "Asia/Damascus",
        offset: 120
    }, {
        id: "Asia/Amman",
        offset: 120
    }, {
        id: "Europe/Athens",
        offset: 120
    }, {
        id: "Asia/Beirut",
        offset: 120
    }, {
        id: "Europe/Bucharest",
        offset: 120
    }, {
        id: "Africa/Cairo",
        offset: 120
    }, {
        id: "Europe/Chisinau",
        offset: 120
    }, {
        id: "Asia/Hebron",
        offset: 120
    }, {
        id: "Europe/Helsinki",
        offset: 120
    }, {
        id: "Europe/Kaliningrad",
        offset: 120
    }, {
        id: "Europe/Kiev",
        offset: 120
    }, {
        id: "Europe/Mariehamn",
        offset: 120
    }, {
        id: "Asia/Nicosia",
        offset: 120
    }, {
        id: "Europe/Riga",
        offset: 120
    }, {
        id: "Europe/Sofia",
        offset: 120
    }, {
        id: "Europe/Tallinn",
        offset: 120
    }, {
        id: "Africa/Tripoli",
        offset: 120
    }, {
        id: "Europe/Vilnius",
        offset: 120
    }, {
        id: "Asia/Jerusalem",
        offset: 120
    }, {
        id: "Africa/Johannesburg",
        offset: 120
    }, {
        id: "Africa/Mbabane",
        offset: 120
    }, {
        id: "Africa/Maseru",
        offset: 120
    }, {
        id: "Asia/Kuwait",
        offset: 180
    }, {
        id: "Asia/Baghdad",
        offset: 180
    }, {
        id: "Asia/Qatar",
        offset: 180
    }, {
        id: "Asia/Bahrain",
        offset: 180
    }, {
        id: "Asia/Riyadh",
        offset: 180
    }, {
        id: "Asia/Aden",
        offset: 180
    }, {
        id: "Africa/Addis_Ababa",
        offset: 180
    }, {
        id: "Indian/Antananarivo",
        offset: 180
    }, {
        id: "Africa/Asmara",
        offset: 180
    }, {
        id: "Africa/Dar_es_Salaam",
        offset: 180
    }, {
        id: "Africa/Djibouti",
        offset: 180
    }, {
        id: "Africa/Kampala",
        offset: 180
    }, {
        id: "Indian/Mayotte",
        offset: 180
    }, {
        id: "Africa/Mogadishu",
        offset: 180
    }, {
        id: "Indian/Comoro",
        offset: 180
    }, {
        id: "Africa/Nairobi",
        offset: 180
    }, {
        id: "Europe/Minsk",
        offset: 180
    }, {
        id: "Europe/Moscow",
        offset: 180
    }, {
        id: "Europe/Simferopol",
        offset: 180
    }, {
        id: "Antarctica/Syowa",
        offset: 180
    }, {
        id: "Europe/Istanbul",
        offset: 180
    }, {
        id: "Asia/Tehran",
        offset: 210
    }, {
        id: "Asia/Yerevan",
        offset: 240
    }, {
        id: "Asia/Baku",
        offset: 240
    }, {
        id: "Asia/Tbilisi",
        offset: 240
    }, {
        id: "Asia/Dubai",
        offset: 240
    }, {
        id: "Asia/Muscat",
        offset: 240
    }, {
        id: "Indian/Mauritius",
        offset: 240
    }, {
        id: "Indian/Reunion",
        offset: 240
    }, {
        id: "Europe/Samara",
        offset: 240
    }, {
        id: "Indian/Mahe",
        offset: 240
    }, {
        id: "Asia/Kabul",
        offset: 270
    }, {
        id: "Indian/Kerguelen",
        offset: 300
    }, {
        id: "Indian/Maldives",
        offset: 300
    }, {
        id: "Antarctica/Mawson",
        offset: 300
    }, {
        id: "Asia/Karachi",
        offset: 300
    }, {
        id: "Asia/Dushanbe",
        offset: 300
    }, {
        id: "Asia/Ashgabat",
        offset: 300
    }, {
        id: "Asia/Tashkent",
        offset: 300
    }, {
        id: "Asia/Qyzylorda",
        offset: 300
    }, {
        id: "Asia/Yekaterinburg",
        offset: 300
    }, {
        id: "Asia/Colombo",
        offset: 330
    }, {
        id: "Asia/Kolkata",
        offset: 330
    }, {
        id: "Asia/Kathmandu",
        offset: 345
    }, {
        id: "Asia/Dhaka",
        offset: 360
    }, {
        id: "Asia/Thimphu",
        offset: 360
    }, {
        id: "Asia/Urumqi",
        offset: 360
    }, {
        id: "Asia/Almaty",
        offset: 360
    }, {
        id: "Indian/Chagos",
        offset: 360
    }, {
        id: "Asia/Bishkek",
        offset: 360
    }, {
        id: "Asia/Omsk",
        offset: 360
    }, {
        id: "Antarctica/Vostok",
        offset: 360
    }, {
        id: "Indian/Cocos",
        offset: 390
    }, {
        id: "Asia/Yangon",
        offset: 390
    }, {
        id: "Indian/Christmas",
        offset: 420
    }, {
        id: "Antarctica/Davis",
        offset: 420
    }, {
        id: "Asia/Hovd",
        offset: 420
    }, {
        id: "Asia/Bangkok",
        offset: 420
    }, {
        id: "Asia/Ho_Chi_Minh",
        offset: 420
    }, {
        id: "Asia/Phnom_Penh",
        offset: 420
    }, {
        id: "Asia/Vientiane",
        offset: 420
    }, {
        id: "Asia/Novosibirsk",
        offset: 420
    }, {
        id: "Asia/Jakarta",
        offset: 420
    }, {
        id: "Australia/Perth",
        offset: 480
    }, {
        id: "Asia/Brunei",
        offset: 480
    }, {
        id: "Asia/Makassar",
        offset: 480
    }, {
        id: "Asia/Macau",
        offset: 480
    }, {
        id: "Asia/Shanghai",
        offset: 480
    }, {
        id: "Asia/Hong_Kong",
        offset: 480
    }, {
        id: "Asia/Irkutsk",
        offset: 480
    }, {
        id: "Asia/Kuala_Lumpur",
        offset: 480
    }, {
        id: "Asia/Manila",
        offset: 480
    }, {
        id: "Asia/Singapore",
        offset: 480
    }, {
        id: "Asia/Taipei",
        offset: 480
    }, {
        id: "Asia/Ulaanbaatar",
        offset: 480
    }, {
        id: "Australia/Eucla",
        offset: 525
    }, {
        id: "Asia/Dili",
        offset: 540
    }, {
        id: "Asia/Jayapura",
        offset: 540
    }, {
        id: "Asia/Tokyo",
        offset: 540
    }, {
        id: "Asia/Pyongyang",
        offset: 540
    }, {
        id: "Asia/Seoul",
        offset: 540
    }, {
        id: "Pacific/Palau",
        offset: 540
    }, {
        id: "Asia/Chita",
        offset: 540
    }, {
        id: "Australia/Adelaide",
        offset: 570
    }, {
        id: "Australia/Darwin",
        offset: 570
    }, {
        id: "Australia/Brisbane",
        offset: 600
    }, {
        id: "Australia/Sydney",
        offset: 600
    }, {
        id: "Pacific/Guam",
        offset: 600
    }, {
        id: "Pacific/Saipan",
        offset: 600
    }, {
        id: "Pacific/Chuuk",
        offset: 600
    }, {
        id: "Antarctica/DumontDUrville",
        offset: 600
    }, {
        id: "Pacific/Port_Moresby",
        offset: 600
    }, {
        id: "Asia/Vladivostok",
        offset: 600
    }, {
        id: "Australia/Lord_Howe",
        offset: 630
    }, {
        id: "Pacific/Bougainville",
        offset: 660
    }, {
        id: "Antarctica/Casey",
        offset: 660
    }, {
        id: "Pacific/Kosrae",
        offset: 660
    }, {
        id: "Pacific/Noumea",
        offset: 660
    }, {
        id: "Pacific/Norfolk",
        offset: 660
    }, {
        id: "Asia/Sakhalin",
        offset: 660
    }, {
        id: "Pacific/Guadalcanal",
        offset: 660
    }, {
        id: "Pacific/Efate",
        offset: 660
    }, {
        id: "Pacific/Fiji",
        offset: 720
    }, {
        id: "Pacific/Tarawa",
        offset: 720
    }, {
        id: "Pacific/Majuro",
        offset: 720
    }, {
        id: "Pacific/Nauru",
        offset: 720
    }, {
        id: "Pacific/Auckland",
        offset: 720
    }, {
        id: "Antarctica/McMurdo",
        offset: 720
    }, {
        id: "Asia/Kamchatka",
        offset: 720
    }, {
        id: "Pacific/Funafuti",
        offset: 720
    }, {
        id: "Pacific/Wake",
        offset: 720
    }, {
        id: "Pacific/Wallis",
        offset: 720
    }, {
        id: "Pacific/Chatham",
        offset: 765
    }, {
        id: "Pacific/Apia",
        offset: 780
    }, {
        id: "Pacific/Fakaofo",
        offset: 780
    }, {
        id: "Pacific/Tongatapu",
        offset: 780
    }, {
        id: "Pacific/Kiritimati",
        offset: 840
    }];

export default m.map(v => {
    v.text = v.id;
    return v;
});
